version: "3.9"

services:

  app:
    build: .
    container_name: bookmyticket-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/movie_project?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: always

  mysql_db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie-project
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mysql_data: